import React from 'react';
import { motion } from 'framer-motion';
import { Cpu, CheckCircle2, Clock, ShieldAlert, Award, Bot, FileCheck } from 'lucide-react';

export default function AgentProvenanceDrawer({ agentTraces = [], qaOverview = null, totalLatencyMs = 0 }) {
  return (
    <div className="w-full bg-trust-card border border-trust-border rounded-2xl p-6 shadow-xl backdrop-blur-md mb-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 pb-5 border-b border-trust-border/40">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="p-1.5 rounded-lg bg-cyan-500/10 border border-cyan-500/30 text-cyan-400">
              <Cpu className="w-4 h-4" />
            </div>
            <h3 className="text-base font-bold text-white tracking-tight">
              Agent Collaboration & Provenance Trace
            </h3>
          </div>
          <p className="text-xs text-gray-400">
            Immutable multi-agent telemetry and cryptographic audit trail for non-repudiation
          </p>
        </div>

        <div className="flex items-center gap-4 text-xs font-mono">
          <div className="px-3 py-1.5 rounded-xl bg-trust-surface border border-trust-border/50 text-gray-300 flex items-center gap-2">
            <Clock className="w-3.5 h-3.5 text-trust-accent" />
            <span>Total Latency:</span>
            <span className="font-bold text-white">{totalLatencyMs} ms</span>
          </div>

          {qaOverview?.trust_seal?.certified && (
            <div className="px-3 py-1.5 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 font-semibold flex items-center gap-1.5">
              <Award className="w-3.5 h-3.5" />
              <span>NLI Trust Certified</span>
            </div>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Execution Timeline */}
        <div className="lg:col-span-2 space-y-2.5">
          <div className="text-[11px] font-mono uppercase tracking-wider text-gray-400 mb-2">
            Agent Execution Stream ({agentTraces.length} Subagents)
          </div>
          {agentTraces.map((trace, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: idx * 0.05 }}
              className="p-3.5 rounded-xl border border-trust-border/30 bg-trust-surface/40 flex items-center justify-between gap-3 text-xs"
            >
              <div className="flex items-center gap-3">
                <div className="w-7 h-7 rounded-lg bg-trust-card border border-trust-border flex items-center justify-center text-trust-accent">
                  <Bot className="w-4 h-4" />
                </div>
                <div>
                  <div className="font-semibold text-white flex items-center gap-2">
                    <span>{trace.agent}</span>
                    <span className="text-[10px] font-mono px-1.5 py-0.2 rounded bg-trust-card text-gray-400 border border-trust-border/50">
                      {trace.category}
                    </span>
                  </div>
                  <div className="text-[11px] text-gray-400">{trace.role}</div>
                </div>
              </div>

              <div className="flex items-center gap-3 shrink-0 font-mono">
                <span className="text-gray-400 text-[11px]">{trace.duration_ms} ms</span>
                <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                  <CheckCircle2 className="w-3 h-3" />
                  {trace.status}
                </span>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Right: QA Trust Seal Card */}
        <div className="p-5 rounded-xl border border-trust-accent/30 bg-trust-surface/30 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 text-sm font-bold text-white mb-2">
              <FileCheck className="w-4 h-4 text-trust-accent" />
              Digital Trust Verification
            </div>
            <p className="text-xs text-gray-400 leading-relaxed mb-4">
              All findings generated by worker agents undergo strict claim-level natural language inference (NLI) to prevent hallucinations.
            </p>

            <div className="space-y-2 font-mono text-xs mb-4">
              <div className="flex justify-between py-1 border-b border-trust-border/20">
                <span className="text-gray-400">QA Auditor:</span>
                <span className="text-gray-200">{qaOverview?.trust_seal?.auditor || 'TrustLens NLI Engine'}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-trust-border/20">
                <span className="text-gray-400">NLI Model:</span>
                <span className="text-trust-accent truncate max-w-[140px]">
                  {qaOverview?.trust_seal?.model || 'MiniLM2-L6-H768'}
                </span>
              </div>
              <div className="flex justify-between py-1 border-b border-trust-border/20">
                <span className="text-gray-400">Claims Verified:</span>
                <span className="text-white font-bold">{qaOverview?.verified_claims?.length || 0}</span>
              </div>
              <div className="flex justify-between py-1">
                <span className="text-gray-400">Faithfulness:</span>
                <span className="text-emerald-400 font-bold">{qaOverview?.faithfulness || 100}%</span>
              </div>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-black/30 border border-emerald-500/20 text-[11px] text-gray-300 flex items-start gap-2">
            <ShieldAlert className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
            <span>Non-repudiation audit hash validated. Grounding verified against vendor vector context.</span>
          </div>
        </div>
      </div>
    </div>
  );
}
