import React from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { BrainCircuit, CheckCheck, Database, FileSearch, Network, ShieldCheck, X } from 'lucide-react';

const STEPS = [
  ['01', 'Ingest a private source', 'A note or text-based file is stored in the active, user-owned workspace and divided into retrievable passages.', Database, 'text-trust-cyan'],
  ['02', 'Retrieve the relevant record', 'The query is matched against the workspace’s passages. OpenAI embeddings are used when available, with a deterministic fallback for degraded operation.', FileSearch, 'text-[#c7b7ff]'],
  ['03', 'Plan the analysis', 'The planner selects only the specialist capabilities needed for the query: claims, evidence, entities, timelines, contradictions, gaps, and synthesis.', BrainCircuit, 'text-trust-amber'],
  ['04', 'Link claims to evidence', 'The response identifies verifiable claims and carries their supporting passages, source authority, and contradictions into the answer contract.', CheckCheck, 'text-trust-green'],
  ['05', 'Make uncertainty explicit', 'TrustLens distinguishes supported, contradicted, and unresolved claims. Unresolved means the evidence is insufficient—not that a statement is false.', ShieldCheck, 'text-[#ffb3bb]'],
  ['06', 'Keep the record reviewable', 'Documents, evidence health, the knowledge map, timeline, and workspace-specific policies remain available after the answer is produced.', Network, 'text-trust-cyan']
];

export default function ArchitectureModal({ isOpen, onClose }) {
  if (!isOpen) return null;
  return <AnimatePresence><div className="fixed inset-0 z-50 grid place-items-center bg-[#050610]/80 p-4 backdrop-blur-md"><motion.div initial={{ opacity: 0, y: 10, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 10, scale: .98 }} transition={{ duration: .18 }} className="glass-panel max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-[24px] p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="editorial-kicker text-[#a2a5bc]">Architecture brief</div><h2 className="mt-2 text-2xl font-extrabold tracking-[-.055em] text-white">How TrustLens earns an answer.</h2><p className="mt-3 max-w-xl text-xs leading-5 text-[#afb1c3]">The product separates what was generated from what the workspace can actually support.</p></div><button onClick={onClose} className="grid h-8 w-8 shrink-0 place-items-center rounded-full text-[#a5a8bc] transition hover:bg-white/[.07] hover:text-white"><X className="h-4 w-4" /></button></div><div className="mt-7 space-y-3">{STEPS.map(([number, title, copy, Icon, color]) => <article key={number} className="flex gap-4 rounded-[18px] border border-white/[.09] bg-white/[.025] p-4"><span className="font-mono text-[10px] text-[#777a92]">{number}</span><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white/[.035] ${color}`}><Icon className="h-4 w-4" /></span><div><h3 className="text-xs font-extrabold text-white">{title}</h3><p className="mt-1.5 text-xs leading-5 text-[#afb1c3]">{copy}</p></div></article>)}</div><div className="mt-5 rounded-2xl border border-trust-amber/25 bg-trust-amber-bg p-4 text-xs leading-5 text-[#f3d99c]"><b className="text-[#ffe5ad]">Important:</b> a confidence percentage is an evidence-grounding signal, not proof of objective truth. Review the linked source passages for consequential decisions.</div></motion.div></div></AnimatePresence>;
}
