import React from 'react';
import { FileText, FolderOpen, Fingerprint, ShieldCheck } from 'lucide-react';

const authorityTone = (authority = 'MEDIUM') => {
  if (authority === 'OFFICIAL' || authority === 'HIGH') return 'border-[#b9cdbd] bg-[var(--tl-sage-100)] text-[var(--tl-sage-600)]';
  if (authority === 'UNVERIFIED') return 'border-[#edcfaa] bg-[#f8ead5] text-[#9b641f]';
  return 'border-[var(--tl-line-300)] bg-[var(--tl-paper-200)] text-[#6d665d]';
};

export default function DocumentLibrary({ documents = [], activeWorkspace }) {
  return <section className="px-[clamp(1.2rem,3vw,2.15rem)] py-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="editorial-kicker flex items-center gap-2 tl-status"><FolderOpen className="h-3.5 w-3.5" />Source register</div><h3 className="mt-2 text-xl font-semibold tracking-[-.045em] text-[#28251f]">Documents with their authority intact.</h3><p className="mt-2 text-xs leading-5 text-[#6d665d]">Every source belongs to <span className="font-semibold text-[#28251f]">{activeWorkspace?.name || 'this workspace'}</span>.</p></div><span className="tl-pill px-3 py-1.5 text-[10px] font-mono">{documents.length} retained source{documents.length === 1 ? '' : 's'}</span></div>{documents.length === 0 ? <div className="mt-6 rounded-[18px] border border-dashed border-[var(--tl-line-300)] bg-[var(--tl-paper-050)] px-5 py-14 text-center"><FileText className="mx-auto h-7 w-7 text-[#9b9287]" /><p className="mt-3 text-sm font-semibold text-[#28251f]">No documents yet</p><p className="mx-auto mt-2 max-w-sm text-xs leading-5 text-[#6d665d]">Add a note, Markdown file, CSV, or plain-text document to start a reviewable evidence record.</p></div> : <div className="mt-6 grid gap-3">{documents.map((document, index) => <article key={document.id} className="group rounded-[16px] border border-[var(--tl-line-300)] bg-[var(--tl-paper-100)] p-4 hover:border-[#c5b6a3] sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--tl-paper-200)] tl-status"><FileText className="h-4.5 w-4.5" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h4 className="truncate text-sm font-semibold text-[#28251f]">{document.title || 'Untitled source'}</h4><span className="text-[10px] font-mono text-[#9b9287]">#{String(index + 1).padStart(2, '0')}</span></div><p className="mt-1 truncate text-[11px] text-[#6d665d]">{document.filename || 'Uploaded document'}</p><p className="mt-3 flex items-center gap-1.5 break-all text-[10px] font-mono text-[#8a8176]"><Fingerprint className="h-3 w-3" />{document.id}</p></div></div><div className="flex flex-wrap items-center gap-2"><span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-mono font-bold ${authorityTone(document.authority_level)}`}><ShieldCheck className="h-3 w-3" />{document.authority_level || 'MEDIUM'}</span><span className="tl-pill px-2.5 py-1 text-[10px] font-mono">{document.ingestion_status || 'READY'}</span></div></div></article>)}</div>}</section>;
}
