import React, { useState } from 'react';
import { Check, FileText, Sparkles, Upload, X, Zap } from 'lucide-react';

const SAMPLE_PACKS = [
  { title: 'Q3 executive review', authority: 'OFFICIAL', description: 'Financial performance, engineering leadership, infrastructure costs, and audit status.', content: 'In Q3 2024, revenue reached $12.5M, a 25% year-over-year increase. The engineering team expanded to 45 engineers led by VP Engineering Alex Rivera. Cloud infrastructure costs decreased to $180K per month after migration to AWS Graviton3. The annual SOC2 Type II audit completed on August 15, 2024 with zero major non-conformities.' },
  { title: 'Product roadmap update', authority: 'HIGH', description: 'A time-bound product decision with a revision to budget and delivery date.', content: 'The enterprise launch was initially planned for November 15, 2024 with a $5.0M budget. Following review on September 1, 2024, the launch moved to March 10, 2025 to incorporate customer feedback and the budget was revised to $7.2M.' }
];

export default function IngestionModal({ isOpen, onClose, onIngest, activeWorkspace }) {
  const [tab, setTab] = useState('note');
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [authority, setAuthority] = useState('HIGH');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  if (!isOpen) return null;
  const ingest = async (event) => { event?.preventDefault(); if (!title.trim() || !content.trim() || loading) return; setLoading(true); setError(null); setResult(null); try { setResult(await onIngest({ title: title.trim(), filename: `${title.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_')}.txt`, raw_content: content.trim(), file_type: 'text', authority_level: authority })); } catch (err) { setError(err.message || 'The document could not be ingested.'); } finally { setLoading(false); } };
  const usePack = (pack) => { setTitle(pack.title); setContent(pack.content); setAuthority(pack.authority); setTab('note'); };
  const readFile = (event) => { const file = event.target.files?.[0]; if (!file) return; setTitle(file.name.replace(/\.[^/.]+$/, '')); const reader = new FileReader(); reader.onload = (loadEvent) => { setContent(loadEvent.target.result || ''); setTab('note'); }; reader.readAsText(file); };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#050610]/80 p-4 backdrop-blur-md"><div className="flex max-h-[92vh] w-full max-w-2xl flex-col overflow-hidden rounded-[24px] border border-white/[.13] bg-[#16182b] shadow-2xl"><header className="flex items-start justify-between border-b border-white/[.08] px-5 py-5 sm:px-6"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#8d6cff]/16 text-[#c7b7ff]"><Upload className="h-5 w-5" /></span><div><h2 className="text-base font-extrabold tracking-[-.035em] text-white">Add source material</h2><p className="mt-1 text-[11px] font-mono text-[#9da0b7]">destination: <span className="text-trust-cyan">{activeWorkspace?.name || 'workspace loading'}</span></p></div></div><button onClick={onClose} className="grid h-8 w-8 place-items-center rounded-full text-[#a5a8bc] transition hover:bg-white/[.07] hover:text-white"><X className="h-4 w-4" /></button></header>
    <nav className="flex gap-1 border-b border-white/[.08] px-5 pt-3 sm:px-6">{[['note', 'Write or paste', FileText], ['sample', 'Sample packs', Zap], ['upload', 'Upload a file', Upload]].map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`inline-flex items-center gap-1.5 border-b-2 px-3 py-2.5 text-[11px] font-bold transition ${tab === id ? 'border-[#a889ff] text-white' : 'border-transparent text-[#9396aa] hover:text-[#d9d9e5]'}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</nav>
    <div className="overflow-y-auto p-5 sm:p-6">{error && <div className="mb-4 rounded-xl border border-trust-red/30 bg-trust-red-bg p-3 text-xs text-[#ffc1c7]">{error}</div>}{result && <div className="mb-5 rounded-2xl border border-trust-green/30 bg-trust-green-bg p-4"><div className="flex items-center gap-2 text-xs font-extrabold text-trust-green"><Check className="h-4 w-4" />Source ingested and ready for verification</div><p className="mt-2 text-[11px] leading-5 text-[#d4e5dd]">{result.chunks_count || 1} semantic chunk(s) were created with claims, entities, and time anchors where found.</p><dl className="mt-3 grid gap-2 sm:grid-cols-2"><div className="rounded-lg border border-trust-green/20 bg-black/[.12] p-2.5"><dt className="text-[9px] font-mono uppercase tracking-[.13em] text-[#8bb9a6]">Document ID</dt><dd className="mt-1 break-all text-[10px] font-mono text-white">{result.document_id || result.id || 'Unavailable'}</dd></div><div className="rounded-lg border border-trust-green/20 bg-black/[.12] p-2.5"><dt className="text-[9px] font-mono uppercase tracking-[.13em] text-[#8bb9a6]">Authority</dt><dd className="mt-1 text-[10px] font-mono text-white">{result.authority_level || authority}</dd></div></dl></div>}
      {tab === 'note' && <form onSubmit={ingest} className="space-y-4"><div className="grid gap-3 sm:grid-cols-[1fr_180px]"><label className="text-[10px] font-mono uppercase tracking-[.12em] text-[#a5a8bc]">Title<input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Board meeting notes" className="mt-1.5 w-full rounded-xl border border-white/[.1] bg-[#0c0d1b] px-3 py-2.5 text-sm normal-case tracking-normal text-white outline-none placeholder:text-[#666a82] focus:border-[#a889ff]" /></label><label className="text-[10px] font-mono uppercase tracking-[.12em] text-[#a5a8bc]">Authority<select value={authority} onChange={(event) => setAuthority(event.target.value)} className="mt-1.5 w-full rounded-xl border border-white/[.1] bg-[#0c0d1b] px-3 py-2.5 text-xs normal-case tracking-normal text-white outline-none focus:border-[#a889ff]"><option value="OFFICIAL">OFFICIAL · final/audited</option><option value="HIGH">HIGH · authoritative</option><option value="MEDIUM">MEDIUM · working note</option><option value="UNVERIFIED">UNVERIFIED · draft</option></select></label></div><label className="block text-[10px] font-mono uppercase tracking-[.12em] text-[#a5a8bc]">Content <span className="float-right normal-case tracking-normal text-[#74778e]">{content.length} characters</span><textarea required rows={10} value={content} onChange={(event) => setContent(event.target.value)} placeholder="Paste the source text you want TrustLens to work from…" className="mt-1.5 w-full resize-y rounded-xl border border-white/[.1] bg-[#0c0d1b] px-3 py-3 text-xs normal-case tracking-normal leading-6 text-white outline-none placeholder:text-[#666a82] focus:border-[#a889ff]" /></label><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-full px-4 py-2.5 text-xs font-bold text-[#b3b5c7]">Close</button><button disabled={loading || !title.trim() || !content.trim()} className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2.5 text-xs font-extrabold text-[#101122] transition hover:bg-[#e9e5ff] disabled:opacity-45">{loading ? <><span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-[#2b2d42]/30 border-t-[#2b2d42]" />Reading source…</> : <><Sparkles className="h-3.5 w-3.5" />Ingest & verify</>}</button></div></form>}
      {tab === 'sample' && <div><p className="text-xs leading-5 text-[#a5a8bc]">Use a small sample dossier to explore source authority, evidence links, and contradiction detection.</p><div className="mt-4 grid gap-3">{SAMPLE_PACKS.map((pack) => <button key={pack.title} onClick={() => usePack(pack)} className="rounded-2xl border border-white/[.09] bg-white/[.025] p-4 text-left transition hover:border-[#a889ff]/35 hover:bg-[#8d6cff]/[.06]"><div className="flex items-center justify-between gap-3"><span className="text-xs font-extrabold text-white">{pack.title}</span><span className="rounded-full border border-[#a889ff]/25 px-2 py-1 text-[9px] font-mono text-[#c7b7ff]">{pack.authority}</span></div><p className="mt-2 text-[11px] leading-5 text-[#a5a8bc]">{pack.description}</p></button>)}</div></div>}
      {tab === 'upload' && <div className="rounded-[20px] border border-dashed border-white/[.16] bg-white/[.02] px-5 py-12 text-center"><Upload className="mx-auto h-8 w-8 text-[#898ca4]" /><p className="mt-4 text-sm font-extrabold text-white">Bring in a text-based file</p><p className="mx-auto mt-2 max-w-sm text-xs leading-5 text-[#9ca0b6]">Plain text, Markdown, CSV, and JSON files are read locally in the browser then prepared as source text.</p><label className="mt-5 inline-flex cursor-pointer items-center gap-2 rounded-full bg-[#8d6cff] px-4 py-2.5 text-xs font-extrabold text-white"><Upload className="h-3.5 w-3.5" />Choose file<input type="file" accept=".txt,.md,.csv,.json" onChange={readFile} className="hidden" /></label></div>}
    </div></div></div>;
}
