import React, { useState } from 'react';
import { CalendarClock, GitBranch, Tag } from 'lucide-react';

export default function KnowledgeGraphTimeline({ entitiesData = null, timelineData = [] }) {
  const [mode, setMode] = useState('timeline');
  const nodes = entitiesData?.nodes || [];
  return <section className="border-x border-b border-white/[.09] bg-[#0c0d1b] px-5 py-7 sm:px-7 sm:py-8"><div className="mx-auto max-w-5xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="editorial-kicker text-[#999cb3]">Knowledge map</div><h3 className="mt-2 text-xl font-extrabold tracking-[-.045em] text-white">Let the connections become visible.</h3><p className="mt-2 text-xs text-[#a1a4ba]">Browse time anchors and recognized entities from your sources.</p></div><div className="flex rounded-full border border-white/[.09] bg-white/[.025] p-1"><button onClick={() => setMode('timeline')} className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[10px] font-bold transition ${mode === 'timeline' ? 'bg-[#8d6cff] text-white' : 'text-[#a7a9bd]'}`}><CalendarClock className="h-3.5 w-3.5" />Timeline ({timelineData.length})</button><button onClick={() => setMode('entities')} className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[10px] font-bold transition ${mode === 'entities' ? 'bg-[#8d6cff] text-white' : 'text-[#a7a9bd]'}`}><GitBranch className="h-3.5 w-3.5" />Entities ({nodes.length})</button></div></div>
    {mode === 'timeline' ? <div className="mt-6">{timelineData.length === 0 ? <Empty icon={CalendarClock} text="No dated events have been extracted. Add source material with dates, decisions, or milestones." /> : <div className="relative ml-2 space-y-4 border-l border-[#8d6cff]/45 pl-6">{timelineData.map((event, index) => <article key={event.id || index} className="relative rounded-[18px] border border-white/[.09] bg-[#15172a] p-4"><span className="absolute -left-[31px] top-5 h-3 w-3 rounded-full border-2 border-[#0c0d1b] bg-[#a889ff] shadow-[0_0_15px_rgba(168,137,255,.7)]" /><span className="inline-flex rounded-full border border-[#7ee8ef]/25 bg-[#7ee8ef]/8 px-2 py-1 text-[10px] font-mono text-trust-cyan">{event.temporal_anchor || event.date_str || 'Time anchor'}</span><p className="mt-3 text-xs leading-6 text-[#e0e1eb]">{event.event_description || event.summary || event.statement}</p>{event.source_document && <p className="mt-3 text-[10px] font-mono text-[#898ca2]">source: {event.source_document}</p>}</article>)}</div>}</div> : <div className="mt-6">{nodes.length === 0 ? <Empty icon={GitBranch} text="No entities have been recognized yet. Ingest sources to start forming a knowledge map." /> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{nodes.map((node, index) => <article key={node.id || index} className="flex items-center justify-between gap-3 rounded-[18px] border border-white/[.09] bg-[#15172a] p-4"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#8d6cff]/13 text-[#c7b7ff]"><Tag className="h-4 w-4" /></span><div className="min-w-0"><p className="truncate text-xs font-extrabold text-white">{node.name || node.id}</p><p className="mt-1 text-[10px] font-mono text-[#9396ac]">{node.type || 'CONCEPT'}</p></div></div>{node.occurrences && <span className="rounded-full border border-white/[.09] px-2 py-1 text-[10px] font-mono text-[#b8baca]">{node.occurrences}×</span>}</article>)}</div>}</div>}
  </div></section>;
}

function Empty({ icon: Icon, text }) { return <div className="rounded-[20px] border border-dashed border-white/[.12] bg-white/[.02] px-5 py-14 text-center"><Icon className="mx-auto h-6 w-6 text-[#777b94]" /><p className="mx-auto mt-3 max-w-sm text-xs leading-5 text-[#989bb1]">{text}</p></div>; }
