import React, { useState } from 'react';
import { Bookmark, Plus, Sliders } from 'lucide-react';

export default function SemanticRulesManager({ rules = [], onAddRule, activeWorkspace }) {
  const [open, setOpen] = useState(false);
  const [type, setType] = useState('AUTHORITY_POLICY');
  const [key, setKey] = useState('');
  const [value, setValue] = useState('');
  const [saving, setSaving] = useState(false);
  const submit = async (event) => { event.preventDefault(); if (!key.trim() || !value.trim() || saving) return; setSaving(true); try { await onAddRule({ rule_type: type, rule_key: key.trim(), rule_value: value.trim() }); setKey(''); setValue(''); setOpen(false); } finally { setSaving(false); } };
  return <section className="border-x border-b border-white/[.09] bg-[#0c0d1b] px-5 py-7 sm:px-7 sm:py-8"><div className="mx-auto max-w-5xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="editorial-kicker text-[#999cb3]">Verification policies</div><h3 className="mt-2 text-xl font-extrabold tracking-[-.045em] text-white">Tell TrustLens how to treat your sources.</h3><p className="mt-2 text-xs leading-5 text-[#a1a4ba]">Rules apply only within {activeWorkspace?.name || 'the active workspace'} and become part of its review context.</p></div><button onClick={() => setOpen((current) => !current)} className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-4 py-2.5 text-xs font-extrabold text-[#111225] transition hover:-translate-y-0.5 hover:bg-[#e9e5ff]"><Plus className="h-3.5 w-3.5" />Add rule</button></div>
    {open && <form onSubmit={submit} className="mt-6 rounded-[20px] border border-[#a889ff]/28 bg-[#8d6cff]/[.07] p-4 sm:p-5"><p className="text-xs font-extrabold text-white">Define a policy</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-[10px] font-mono text-[#a6a9be]">TYPE<select value={type} onChange={(event) => setType(event.target.value)} className="mt-1.5 w-full rounded-xl border border-white/[.1] bg-[#0d0e1d] px-3 py-2.5 text-xs text-white outline-none"><option value="AUTHORITY_POLICY">AUTHORITY POLICY</option><option value="CONTRADICTION_POLICY">CONTRADICTION POLICY</option><option value="CITATION_CONSTRAINT">CITATION CONSTRAINT</option></select></label><label className="text-[10px] font-mono text-[#a6a9be]">TOPIC<input required value={key} onChange={(event) => setKey(event.target.value)} placeholder="e.g. Financial reports" className="mt-1.5 w-full rounded-xl border border-white/[.1] bg-[#0d0e1d] px-3 py-2.5 text-xs text-white outline-none placeholder:text-[#696d83]" /></label><label className="text-[10px] font-mono text-[#a6a9be]">DIRECTIVE<input required value={value} onChange={(event) => setValue(event.target.value)} placeholder="e.g. Prefer official source" className="mt-1.5 w-full rounded-xl border border-white/[.1] bg-[#0d0e1d] px-3 py-2.5 text-xs text-white outline-none placeholder:text-[#696d83]" /></label></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-full px-3 py-2 text-xs font-bold text-[#b4b6c7]">Cancel</button><button disabled={saving} className="rounded-full bg-[#8d6cff] px-4 py-2 text-xs font-extrabold text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save policy'}</button></div></form>}
    <div className="mt-6 grid gap-3">{rules.length === 0 ? <div className="rounded-[20px] border border-dashed border-white/[.12] bg-white/[.02] px-5 py-12 text-center"><Sliders className="mx-auto h-6 w-6 text-[#777b94]" /><p className="mt-3 text-xs text-[#989bb1]">No additional policies yet. Default verification behavior is active.</p></div> : rules.map((rule, index) => <article key={rule.id || index} className="flex flex-col gap-3 rounded-[18px] border border-white/[.09] bg-[#15172a] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#8d6cff]/13 text-[#c7b7ff]"><Bookmark className="h-4 w-4" /></span><div><p className="text-xs font-extrabold text-white">{rule.rule_key}</p><p className="mt-1 text-xs leading-5 text-[#b2b4c6]">{rule.rule_value}</p></div></div><span className="w-fit rounded-full border border-white/[.09] bg-black/[.12] px-2.5 py-1 text-[10px] font-mono text-[#b9bbca]">{rule.rule_type}</span></article>)}</div>
  </div></section>;
}
